# https://github.com/drduh/YubiKey-Guide#ssh
- apt:
    pkg:
    - gnupg2
    - gnupg-agent
    - dirmngr
    - cryptsetup
    - scdaemon
    - pcscd
    - secure-delete
    - hopenpgp-tools
    - yubikey-personalization
  become: yes

- name: ensure public keys are imported
  shell: gpg --keyserver {{ item.keyserver }} --recv-keys {{ item.keyId }}
  with_items: "{{ yubikey_gpg_keys_to_import }}"

- name: create ownertrust files
  copy:
    content: "{{ item.keyId }}:{{ item.trust }}:\n"
    dest: /tmp/ownertrust_{{ item.keyId }}
  with_items: "{{ yubikey_gpg_keys_to_import }}"

- name: ensure ownertrust is imported
  shell: gpg --import-ownertrust /tmp/ownertrust_{{ item.keyId }}
  with_items: "{{ yubikey_gpg_keys_to_import }}"

- template:
    src: templates/gpg-agent.conf.j2
    dest: /home/olorenz/.gnupg/gpg-agent.conf

- copy:
    src: templates/profile_gpg_agent.source
    dest: ~/.profile_gpg_agent.sh

- lineinfile:
    dest: "~/.profile"
    line: "source ~/.profile_gpg_agent.sh"
    regexp: '^source ~\/\.profile_gpg_agent\.sh'

- lineinfile:
    dest: "~/.bashrc"
    create: yes
    state: present
    line: "export GPG_TTY=\"$(tty)\""
    regexp: "^export GPG_TTY"

- lineinfile:
    dest: "~/.bashrc"
    create: yes
    state: present
    line: "export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)"
    regexp: "^export SSH_AUTH_SOCK"

- lineinfile:
    dest: "~/.bashrc"
    create: yes
    state: present
    line: "gpgconf --launch gpg-agent"
    regexp: "^gpgconf --launch"

- shell: gpg-connect-agent reloadagent /bye
