# https://github.com/drduh/YubiKey-Guide#ssh
- apt:
    pkg:
    - gnupg2
    - gnupg-agent
    - dirmngr
    - cryptsetup
    - scdaemon
    - pcscd
    - secure-delete
    - hopenpgp-tools
    - yubikey-personalization
  become: yes

- name: ensure public keys are imported
  shell: gpg --keyserver {{ item.keyserver }} --recv-keys {{ item.keyId }}
  with_items: "{{ yubikey_gpg_keys_to_import }}"

- name: create ownertrust files
  copy:
    content: "{{ item.keyId }}:{{ item.trust }}:\n"
    dest: /tmp/ownertrust_{{ item.keyId }}
  with_items: "{{ yubikey_gpg_keys_to_import }}"

- name: ensure ownertrust is imported
  shell: gpg --import-ownertrust /tmp/ownertrust_{{ item.keyId }}
  with_items: "{{ yubikey_gpg_keys_to_import }}"

- template:
    src: templates/gpg-agent.conf.j2
    dest: /home/olorenz/.gnupg/gpg-agent.conf

- blockinfile:
    path: /home/olorenz/.profile
    block: |
      [ -f ~/.gpg-agent-info ] && source ~/.gpg-agent-info
      if [ -S "${GPG_AGENT_INFO%%:*}" ]; then
        export GPG_AGENT_INFO
        export SSH_AUTH_SOCK
        export SSH_AGENT_PID
      else
        eval $(gpg-agent --daemon --write-env-file ~/.gpg-agent-info)
      fi

- shell: gpg-connect-agent reloadagent /bye
